apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner
  namespace: local-path-storage
spec:
  interval: 1h
  chart:
    spec:
      chart: ./gitops/flux/infrastructure/local-path-provisioner/charts/local-path-provisioner
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: docker.io/rancher/local-path-provisioner
      tag: v0.0.36
    storageClass:
      create: true
      name: local-path
      defaultClass: true
      reclaimPolicy: Delete
    nodePathMap:
      - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
        paths:
          - /var/local-path-provisioner
    configmap:
      name: local-path-config
      helperPod:
        tolerations:
          - key: node.kubernetes.io/disk-pressure
            operator: Exists
            effect: NoSchedule
