apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
spec:
  distribution:
    version: "2.x"
    registry: "ghcr.io/fluxcd"
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
  cluster:
    type: kubernetes
    multitenant: false
    networkPolicy: false
  sync:
    kind: GitRepository
    url: "https://github.com/jjtimi888/promox-terraform-talos-linux.git"
    ref: "refs/heads/main"
    path: "./gitops/flux/clusters/homelab-cluster"
