apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default-l2-policy
  namespace: kube-system
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: talos-worker-01
  interfaces:
    - ^e.*
  externalIPs: true
  loadBalancerIPs: true
